# Generated by Django 4.2.6 on 2023-10-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_products_p_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products_Payments_Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("m_date", models.DateTimeField(auto_created=True)),
                ("p_name", models.CharField(max_length=50)),
                ("price", models.BigIntegerField()),
                ("desc", models.TextField()),
                ("p_img", models.ImageField(upload_to="")),
                (
                    "status",
                    models.CharField(
                        default="Pending", max_length=254, verbose_name="Payment Status"
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(max_length=40, verbose_name="Order ID"),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=36, verbose_name="Payment ID"),
                ),
                (
                    "signature_id",
                    models.CharField(max_length=128, verbose_name="Signature ID"),
                ),
            ],
        ),
    ]
